### PR TITLE
cache control header with 30 minutes of max age in nginx config

### PR DESCRIPTION
**Pull request by ltkum**
[if you want to test](http://tileserver.dev.bgdi.ch/)

### CODE REVIEW

**Comment by ltkum** [comment]
ping @danduk82

**Comment by danduk82** [comment]
Hi @ltkum , from what I see, there are a few bugs:
- [ ] resources with double cache control header (e.g. `favicon.ico`)
- [ ] resources with no cache-control (such as `relief.json`)
could you please fix them?

Thanks in advance

**Comment by ltkum** [comment]
@danduk82 
cache control headers are in order. 
Resources that have client or server error codes (4xx and 5xx) won't have any, other resources have one. ( https://nginx.org/en/docs/http/ngx_http_headers_module.html#expires for the exhaustive list of 2xx and 3xx codes that return a caching header with the expire directive). I used the expire directive as it overrides the header if another resource (for example: tileserver) sets another max age. 

Only thing remaining is that wmts jsons, wmts tiles and the favicon have twice the header "Accept-ranges: bytes". The problem does not appear on local deploys (and I do not set this header in nginx) which makes me think that this behaviour is linked to varnish.

**Comment by danduk82** [comment]
@ltkum , could you please check why `relief.json` has still no header?

**Comment by swissgis3084** [comment]
we won't be having a relief in v006

**Comment by danduk82** [comment]
@ltkum , merged. Please coordinate with @swissmup for deploy on int/prod

**Comment by ltkum** [comment]
@danduk82 I already checked yesterday with @swissmap . swissmup isn't with us anymore ^^.

**Pull request merged**
